--- #YAML:1.0
name:                Module-Compile-TT
version:             0.02
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Module::Compile:               0
    ok:                            0
    Template:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
